# Generated by Django 4.0.5 on 2022-06-25 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=64)),
                ('lname', models.CharField(max_length=64)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=3)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('given_at_age_from_year', models.IntegerField()),
                ('given_at_age_from_month', models.IntegerField()),
                ('given_at_age_from_weeks', models.IntegerField()),
                ('details', models.CharField(max_length=512)),
                ('gender', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField()),
                ('vac_taken_date', models.DateField()),
                ('recipient_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VacciSafeApp.recipients')),
                ('vaccine_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VacciSafeApp.vaccines')),
            ],
        ),
    ]
