# Generated by Django 4.0.5 on 2022-06-29 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VacciSafeApp', '0003_delete_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipients',
            unique_together={('fname', 'lname')},
        ),
    ]
