# Generated by Django 4.0.5 on 2022-06-29 05:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VacciSafeApp', '0004_alter_recipients_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipients',
            unique_together={('user_fk', 'fname', 'lname')},
        ),
    ]
