# Generated by Django 4.0.5 on 2022-06-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacciSafeApp', '0005_alter_recipients_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccines',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
